name: admin-ui

on:
  push:
    paths:
      - "apps/admin-ui/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: yarn install --frozen-lockfile
        working-directory: apps/admin-ui
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn build
        working-directory: apps/admin-ui
        env:
          VITE_GITLAB_TOKEN: ${{ secrets.GITLAB_READ_TOKEN }}
          VITE_ANALYTICS_API_KEY: ${{ secrets.ANALYTICS_API_KEY }}
